;[
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
  {
    id: '',
    title: 'string',
    active: 'true',
    description: 'string',
    rows: [{ description: 'descricaofodase', productId: 'wqjfkasdjfkdjfkj' }],
    products: 'Types.ObjectId[]',
    icon: 'string',
  },
]
