import Head from 'next/head'
import '../styles/globals.css'
import { AuthProvider } from '../contexts/AuthContext'

import { SnackbarProvider } from 'notistack'
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Herbal Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>
        <SnackbarProvider maxSnack={5}>
          <Component {...pageProps} />
        </SnackbarProvider>
      </AuthProvider>
    </>
  )
}
