import Head from 'next/head'
import '../styles/globals.css'
import { AuthProvider } from '../contexts/AuthContext'
import MainLayout from '../components/MainLayout'
export default function App({ Component, pageProps }) {
  return (
    <AuthProvider>
      <Head>
        <title>Herbal Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </AuthProvider>
  )
}
