import Head from "next/head";
import Image from "next/image";
import { Card } from 'antd'
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Herbal Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen bg-black">
        <div className="md:container">
          <h1>Bom dia</h1>
        </div>
      </main>
    </>
  );
}
